/// Original, bundled clue bank. All play and hints work offline.
const clueBank = <String, String>{
  'APPLE': 'Fruit that grows in an orchard',
  'BEACH': 'Sandy meeting of land and sea',
  'CANDY': 'A sweet treat',
  'DRAMA': 'A serious stage play',
  'EARTH': 'Our home planet',
  'SMILE': 'A happy expression',
  'PAPER': 'Material used for a written letter',
  'OCEAN': 'A vast body of salt water',
  'OLIVE': 'Small fruit pressed for oil',
  'NIGHT': 'Time between sunset and sunrise',
  'RIVER': 'Water flowing toward the sea',
  'STONE': 'A small piece of rock',
  'CLOUD': 'A visible mass of water droplets in the sky',
  'BREAD': 'Food baked from flour and yeast',
  'CHAIR': 'A seat for one person',
  'TRAIN': 'Transport that runs on rails',
  'PLANT': 'A living thing with roots',
  'TIGER': 'A large striped cat',
  'HORSE': 'Animal ridden with a saddle',
  'MOUSE': 'Small rodent, or a computer pointer device',
  'HOUSE': 'A building to live in',
  'LIGHT': 'What makes things visible',
  'SOUND': 'What the ears detect',
  'GREEN': 'The color of fresh grass',
  'BLACK': 'The color of coal',
  'WHITE': 'The color of fresh snow',
  'WATER': 'Liquid with the formula H2O',
  'FLAME': 'The glowing part of a fire',
  'FROST': 'Ice crystals on a cold window',
  'STORM': 'Severe weather with wind and rain',
  'BLOOM': 'To produce flowers',
  'GRAPE': 'Small fruit that grows in bunches',
  'PEACH': 'A fuzzy stone fruit',
  'LEMON': 'A sour yellow citrus fruit',
  'MANGO': 'A tropical fruit with a large stone',
  'BERRY': 'A small juicy fruit',
  'PEARL': 'A gem formed inside an oyster',
  'CORAL': 'Reef-building marine animal',
  'WHALE': 'A huge marine mammal',
  'SHARK': 'A fish with several rows of teeth',
  'SHELL': 'A mollusk’s protective covering',
  'BRUSH': 'Tool for painting or tidying hair',
  'CLOCK': 'A device that tells time',
  'SPOON': 'Utensil for eating soup',
  'PLATE': 'A flat dish for food',
  'GLASS': 'Transparent material used in windows',
  'SHELF': 'A horizontal storage ledge',
  'DREAM': 'An experience during sleep',
  'SLEEP': 'A nightly state of rest',
  'HEART': 'Organ that pumps blood',
  'BRAIN': 'Organ inside the skull',
  'DANCE': 'Move rhythmically to music',
  'MUSIC': 'Organized sound with rhythm or melody',
  'PIANO': 'Keyboard instrument with strings and hammers',
  'DRUM': 'Instrument played by striking a membrane',
  'FLUTE': 'Wind instrument held sideways',
  'VIOLA': 'String instrument larger than a violin',
  'MAPLE': 'Tree associated with syrup',
  'BIRCH': 'Tree often recognized by its pale bark',
  'CEDAR': 'Fragrant evergreen tree',
  'FERN': 'Plant with fronds instead of flowers',
  'ROSE': 'Flower often associated with love',
  'LILY': 'Flower with large trumpet-like blooms',
  'TULIP': 'Spring flower grown from a bulb',
  'DAISY': 'Flower with a yellow center and white petals',
  'BOOK': 'Bound pages for reading',
  'POEM': 'Writing arranged in verse',
  'STORY': 'An account of events',
  'NOVEL': 'A long work of fiction',
  'MOON': 'Earth’s natural satellite',
  'STAR': 'A luminous ball of gas in space',
  'COMET': 'Icy space object with a tail near the Sun',
  'ORBIT': 'Path around a planet or star',
  'SPACE': 'The region beyond Earth’s atmosphere',
  'SOLAR': 'Relating to the Sun',
  'METAL': 'Material such as iron or copper',
  'STEEL': 'An alloy of iron and carbon',
  'COPPER': 'Reddish metal used in electrical wiring',
  'SILVER': 'Precious metal with symbol Ag',
  'GOLD': 'Precious metal with symbol Au',
  'IRON': 'Metal with symbol Fe',
  'EAGLE': 'Bird of prey with keen vision',
  'ROBIN': 'Bird known for a red or orange breast',
  'CRANE': 'Long-legged bird, or a lifting machine',
  'RAVEN': 'A large black bird',
  'OTTER': 'Playful aquatic mammal',
  'ZEBRA': 'Striped African equine',
  'PANDA': 'Bear associated with bamboo',
  'CAMEL': 'Desert animal with humps',
  'FIELD': 'An open area of land',
  'TRAIL': 'A path through the countryside',
  'HILL': 'A raised area of land smaller than a mountain',
  'VALLEY': 'Low land between hills',
  'BASIL': 'Aromatic herb used in pesto',
  'THYME': 'A small-leaved cooking herb',
  'SAGE': 'A cooking herb, or a wise person',
  'MINT': 'A refreshing herb',
};

const categoryBank = <String, List<String>>{
  'Orchard fruit': ['APPLE', 'PEAR', 'PEACH', 'PLUM', 'CHERRY', 'APRICOT'],
  'Kitchen utensils': ['SPOON', 'FORK', 'LADLE', 'WHISK', 'SPATULA', 'TONGS'],
  'Musical instruments': ['PIANO', 'FLUTE', 'VIOLIN', 'DRUM', 'OBOE', 'HARP'],
  'Weather': ['RAIN', 'SNOW', 'HAIL', 'SLEET', 'FOG', 'WIND'],
  'Trees': ['MAPLE', 'BIRCH', 'CEDAR', 'OAK', 'ELM', 'PINE'],
  'Flowers': ['ROSE', 'LILY', 'TULIP', 'DAISY', 'IRIS', 'POPPY'],
  'Precious and useful metals': [
    'GOLD',
    'SILVER',
    'COPPER',
    'IRON',
    'TIN',
    'ZINC',
  ],
  'Ocean life': ['WHALE', 'SHARK', 'CORAL', 'SQUID', 'OCTOPUS', 'DOLPHIN'],
  'Birds': ['EAGLE', 'ROBIN', 'RAVEN', 'SPARROW', 'FINCH', 'OWL'],
  'Writing forms': ['POEM', 'NOVEL', 'ESSAY', 'MEMOIR', 'FABLE', 'SONNET'],
  'Shapes': ['CIRCLE', 'SQUARE', 'TRIANGLE', 'OVAL', 'HEXAGON', 'PENTAGON'],
  'Things worn on feet': [
    'BOOTS',
    'SHOES',
    'SOCKS',
    'SANDALS',
    'SLIPPERS',
    'SKATES',
  ],
  'Cooking methods': ['BAKE', 'ROAST', 'STEAM', 'FRY', 'GRILL', 'POACH'],
  'Ways to move': ['WALK', 'RUN', 'SKIP', 'CRAWL', 'HOP', 'JOG'],
  'School subjects': [
    'HISTORY',
    'BIOLOGY',
    'PHYSICS',
    'CHEMISTRY',
    'ALGEBRA',
    'GEOGRAPHY',
  ],
  'Board games': [
    'CHESS',
    'CHECKERS',
    'REVERSI',
    'SCRABBLE',
    'LUDO',
    'BACKGAMMON',
  ],
  'Parts of a book': [
    'COVER',
    'SPINE',
    'INDEX',
    'PREFACE',
    'CHAPTER',
    'GLOSSARY',
  ],
  'Computer equipment': [
    'KEYBOARD',
    'MONITOR',
    'MOUSE',
    'PRINTER',
    'SCANNER',
    'ROUTER',
  ],
  'Words before cake': ['PAN', 'CUP', 'CHEESE', 'FRUIT', 'POUND', 'SPONGE'],
  'Words before room': ['BED', 'BATH', 'CLASS', 'BALL', 'SHOW', 'STORE'],
  'Words before light': ['SUN', 'MOON', 'STAR', 'FLASH', 'SPOT', 'DAY'],
  'Words before work': ['HOME', 'TEAM', 'FRAME', 'PAPER', 'FOOT', 'NET'],
  'Words before fall': ['WATER', 'SNOW', 'RAIN', 'NIGHT', 'DOWN', 'FREE'],
  'Words before man': ['MAIL', 'FIRE', 'SNOW', 'SAND', 'FISHER', 'POLICE'],
};

// Common seven-distinct-letter words guarantee a playable Spelling Bee pangram.
const beePangrams = [
  'PAINTER',
  'RETAINS',
  'NASTIER',
  'TRAINED',
  'DEALING',
  'READING',
  'CENTRAL',
  'ARTICLE',
  'CHARITY',
  'HARMONY',
  'FLOWERS',
  'NETWORK',
  'JOURNEY',
  'CAPTION',
  'CAUTION',
  'NOTICES',
  'SECTION',
  'DETAILS',
  'ENTAILS',
  'TANGLED',
  'GARDENS',
  'DANGERS',
  'FOLDERS',
  'WONDERS',
  'CLOVERS',
  'CROWNED',
  'PANTHER',
  'THUNDER',
  'HUNTERS',
  'CLUSTER',
  'CRUMBLE',
  'BLANKET',
];
